// Generated by CoffeeScript 1.12.6
var WAD, fs, w;

fs = require('fs');

WAD = require('../src/wad.js');

w = WAD.read(fs.readFileSync('test.wad'));

QUnit.test('WAD reading', function(assert) {
  assert.strictEqual(w.ptype, "PWAD", "PWAD/IWAD detection");
  assert.strictEqual(w.lumps[0].name.toString('ascii'), "TESTNAME", "lumpname reading");
  assert.strictEqual(w.lumps[0].data.length, 12, "lump data reading: offsets and length");
  return assert.strictEqual(w.lumps[0].data.toString('ascii'), "Hello World!", "lump data reading: content");
});

QUnit.test('WAD writing', function(assert) {
  if ((w != null) && (w.write != null)) {
    return assert.equal(w.write().toString('hex'), fs.readFileSync('test.wad', {
      encoding: 'hex'
    }), "WAD serializing");
  }
});
