// Generated by CoffeeScript 1.12.6
var WLump,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

WLump = (function() {
  function WLump(wad, data, name) {
    this.wad = wad;
    this.write = bind(this.write, this);
    this.getSize = bind(this.getSize, this);
    this.data = new Buffer(data);
    this.name = name.toString('ascii');
    while (this.name.endsWith("\x00")) {
      this.name = this.name.slice(0, -1);
    }
    this.strData = this.data.toString('utf-8');
  }

  WLump.prototype.getSize = function() {
    return this.data.length;
  };

  WLump.prototype.write = function(bf) {
    var c, i, len, ref, results;
    ref = this.data.toString('ascii');
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      c = ref[i];
      results.push(bf.writeUInt8((new Buffer(c, 'ascii')).readUInt8()));
    }
    return results;
  };

  return WLump;

})();

module.exports = WLump;
